const githubResult = """
{
  "total_count": 9040,
  "incomplete_results": false,
  "items": [
    {
      "login": "Filipe",
      "id": 27786693,
      "node_id": "MDQ6VXNlcjI3Nzg2Njkz",
      "avatar_url": "https://avatars.githubusercontent.com/u/27786693?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Filipe",
      "html_url": "https://github.com/Filipe",
      "followers_url": "https://api.github.com/users/Filipe/followers",
      "following_url": "https://api.github.com/users/Filipe/following{/other_user}",
      "gists_url": "https://api.github.com/users/Filipe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Filipe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Filipe/subscriptions",
      "organizations_url": "https://api.github.com/users/Filipe/orgs",
      "repos_url": "https://api.github.com/users/Filipe/repos",
      "events_url": "https://api.github.com/users/Filipe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Filipe/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipedeschamps",
      "id": 4248081,
      "node_id": "MDQ6VXNlcjQyNDgwODE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4248081?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipedeschamps",
      "html_url": "https://github.com/filipedeschamps",
      "followers_url": "https://api.github.com/users/filipedeschamps/followers",
      "following_url": "https://api.github.com/users/filipedeschamps/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipedeschamps/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipedeschamps/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipedeschamps/subscriptions",
      "organizations_url": "https://api.github.com/users/filipedeschamps/orgs",
      "repos_url": "https://api.github.com/users/filipedeschamps/repos",
      "events_url": "https://api.github.com/users/filipedeschamps/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipedeschamps/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ocefpaf",
      "id": 950575,
      "node_id": "MDQ6VXNlcjk1MDU3NQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/950575?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ocefpaf",
      "html_url": "https://github.com/ocefpaf",
      "followers_url": "https://api.github.com/users/ocefpaf/followers",
      "following_url": "https://api.github.com/users/ocefpaf/following{/other_user}",
      "gists_url": "https://api.github.com/users/ocefpaf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ocefpaf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ocefpaf/subscriptions",
      "organizations_url": "https://api.github.com/users/ocefpaf/orgs",
      "repos_url": "https://api.github.com/users/ocefpaf/repos",
      "events_url": "https://api.github.com/users/ocefpaf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ocefpaf/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipesilva",
      "id": 4172079,
      "node_id": "MDQ6VXNlcjQxNzIwNzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4172079?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipesilva",
      "html_url": "https://github.com/filipesilva",
      "followers_url": "https://api.github.com/users/filipesilva/followers",
      "following_url": "https://api.github.com/users/filipesilva/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipesilva/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipesilva/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipesilva/subscriptions",
      "organizations_url": "https://api.github.com/users/filipesilva/orgs",
      "repos_url": "https://api.github.com/users/filipesilva/repos",
      "events_url": "https://api.github.com/users/filipesilva/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipesilva/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipelinhares",
      "id": 2338778,
      "node_id": "MDQ6VXNlcjIzMzg3Nzg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2338778?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipelinhares",
      "html_url": "https://github.com/filipelinhares",
      "followers_url": "https://api.github.com/users/filipelinhares/followers",
      "following_url": "https://api.github.com/users/filipelinhares/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipelinhares/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipelinhares/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipelinhares/subscriptions",
      "organizations_url": "https://api.github.com/users/filipelinhares/orgs",
      "repos_url": "https://api.github.com/users/filipelinhares/repos",
      "events_url": "https://api.github.com/users/filipelinhares/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipelinhares/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipeximenes",
      "id": 1180884,
      "node_id": "MDQ6VXNlcjExODA4ODQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1180884?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipeximenes",
      "html_url": "https://github.com/filipeximenes",
      "followers_url": "https://api.github.com/users/filipeximenes/followers",
      "following_url": "https://api.github.com/users/filipeximenes/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipeximenes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipeximenes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipeximenes/subscriptions",
      "organizations_url": "https://api.github.com/users/filipeximenes/orgs",
      "repos_url": "https://api.github.com/users/filipeximenes/repos",
      "events_url": "https://api.github.com/users/filipeximenes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipeximenes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipecosta90",
      "id": 5832149,
      "node_id": "MDQ6VXNlcjU4MzIxNDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5832149?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipecosta90",
      "html_url": "https://github.com/filipecosta90",
      "followers_url": "https://api.github.com/users/filipecosta90/followers",
      "following_url": "https://api.github.com/users/filipecosta90/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipecosta90/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipecosta90/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipecosta90/subscriptions",
      "organizations_url": "https://api.github.com/users/filipecosta90/orgs",
      "repos_url": "https://api.github.com/users/filipecosta90/repos",
      "events_url": "https://api.github.com/users/filipecosta90/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipecosta90/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipenevola",
      "id": 437372,
      "node_id": "MDQ6VXNlcjQzNzM3Mg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/437372?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipenevola",
      "html_url": "https://github.com/filipenevola",
      "followers_url": "https://api.github.com/users/filipenevola/followers",
      "following_url": "https://api.github.com/users/filipenevola/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipenevola/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipenevola/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipenevola/subscriptions",
      "organizations_url": "https://api.github.com/users/filipenevola/orgs",
      "repos_url": "https://api.github.com/users/filipenevola/repos",
      "events_url": "https://api.github.com/users/filipenevola/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipenevola/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipealvesdef",
      "id": 10976512,
      "node_id": "MDQ6VXNlcjEwOTc2NTEy",
      "avatar_url": "https://avatars.githubusercontent.com/u/10976512?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipealvesdef",
      "html_url": "https://github.com/filipealvesdef",
      "followers_url": "https://api.github.com/users/filipealvesdef/followers",
      "following_url": "https://api.github.com/users/filipealvesdef/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipealvesdef/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipealvesdef/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipealvesdef/subscriptions",
      "organizations_url": "https://api.github.com/users/filipealvesdef/orgs",
      "repos_url": "https://api.github.com/users/filipealvesdef/repos",
      "events_url": "https://api.github.com/users/filipealvesdef/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipealvesdef/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipebteixeira98",
      "id": 26986586,
      "node_id": "MDQ6VXNlcjI2OTg2NTg2",
      "avatar_url": "https://avatars.githubusercontent.com/u/26986586?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipebteixeira98",
      "html_url": "https://github.com/filipebteixeira98",
      "followers_url": "https://api.github.com/users/filipebteixeira98/followers",
      "following_url": "https://api.github.com/users/filipebteixeira98/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipebteixeira98/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipebteixeira98/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipebteixeira98/subscriptions",
      "organizations_url": "https://api.github.com/users/filipebteixeira98/orgs",
      "repos_url": "https://api.github.com/users/filipebteixeira98/repos",
      "events_url": "https://api.github.com/users/filipebteixeira98/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipebteixeira98/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipecancio",
      "id": 13178261,
      "node_id": "MDQ6VXNlcjEzMTc4MjYx",
      "avatar_url": "https://avatars.githubusercontent.com/u/13178261?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipecancio",
      "html_url": "https://github.com/filipecancio",
      "followers_url": "https://api.github.com/users/filipecancio/followers",
      "following_url": "https://api.github.com/users/filipecancio/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipecancio/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipecancio/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipecancio/subscriptions",
      "organizations_url": "https://api.github.com/users/filipecancio/orgs",
      "repos_url": "https://api.github.com/users/filipecancio/repos",
      "events_url": "https://api.github.com/users/filipecancio/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipecancio/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipekiss",
      "id": 48519,
      "node_id": "MDQ6VXNlcjQ4NTE5",
      "avatar_url": "https://avatars.githubusercontent.com/u/48519?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipekiss",
      "html_url": "https://github.com/filipekiss",
      "followers_url": "https://api.github.com/users/filipekiss/followers",
      "following_url": "https://api.github.com/users/filipekiss/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipekiss/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipekiss/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipekiss/subscriptions",
      "organizations_url": "https://api.github.com/users/filipekiss/orgs",
      "repos_url": "https://api.github.com/users/filipekiss/repos",
      "events_url": "https://api.github.com/users/filipekiss/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipekiss/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipeamoreira",
      "id": 8424,
      "node_id": "MDQ6VXNlcjg0MjQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8424?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipeamoreira",
      "html_url": "https://github.com/filipeamoreira",
      "followers_url": "https://api.github.com/users/filipeamoreira/followers",
      "following_url": "https://api.github.com/users/filipeamoreira/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipeamoreira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipeamoreira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipeamoreira/subscriptions",
      "organizations_url": "https://api.github.com/users/filipeamoreira/orgs",
      "repos_url": "https://api.github.com/users/filipeamoreira/repos",
      "events_url": "https://api.github.com/users/filipeamoreira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipeamoreira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Eastrall",
      "id": 4021025,
      "node_id": "MDQ6VXNlcjQwMjEwMjU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4021025?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Eastrall",
      "html_url": "https://github.com/Eastrall",
      "followers_url": "https://api.github.com/users/Eastrall/followers",
      "following_url": "https://api.github.com/users/Eastrall/following{/other_user}",
      "gists_url": "https://api.github.com/users/Eastrall/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Eastrall/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Eastrall/subscriptions",
      "organizations_url": "https://api.github.com/users/Eastrall/orgs",
      "repos_url": "https://api.github.com/users/Eastrall/repos",
      "events_url": "https://api.github.com/users/Eastrall/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Eastrall/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipebarcos",
      "id": 303141,
      "node_id": "MDQ6VXNlcjMwMzE0MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/303141?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipebarcos",
      "html_url": "https://github.com/filipebarcos",
      "followers_url": "https://api.github.com/users/filipebarcos/followers",
      "following_url": "https://api.github.com/users/filipebarcos/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipebarcos/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipebarcos/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipebarcos/subscriptions",
      "organizations_url": "https://api.github.com/users/filipebarcos/orgs",
      "repos_url": "https://api.github.com/users/filipebarcos/repos",
      "events_url": "https://api.github.com/users/filipebarcos/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipebarcos/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipebraida",
      "id": 2746730,
      "node_id": "MDQ6VXNlcjI3NDY3MzA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2746730?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipebraida",
      "html_url": "https://github.com/filipebraida",
      "followers_url": "https://api.github.com/users/filipebraida/followers",
      "following_url": "https://api.github.com/users/filipebraida/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipebraida/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipebraida/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipebraida/subscriptions",
      "organizations_url": "https://api.github.com/users/filipebraida/orgs",
      "repos_url": "https://api.github.com/users/filipebraida/repos",
      "events_url": "https://api.github.com/users/filipebraida/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipebraida/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipeleonelbatista",
      "id": 20867392,
      "node_id": "MDQ6VXNlcjIwODY3Mzky",
      "avatar_url": "https://avatars.githubusercontent.com/u/20867392?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipeleonelbatista",
      "html_url": "https://github.com/filipeleonelbatista",
      "followers_url": "https://api.github.com/users/filipeleonelbatista/followers",
      "following_url": "https://api.github.com/users/filipeleonelbatista/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipeleonelbatista/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipeleonelbatista/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipeleonelbatista/subscriptions",
      "organizations_url": "https://api.github.com/users/filipeleonelbatista/orgs",
      "repos_url": "https://api.github.com/users/filipeleonelbatista/repos",
      "events_url": "https://api.github.com/users/filipeleonelbatista/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipeleonelbatista/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipeflop",
      "id": 4410043,
      "node_id": "MDQ6VXNlcjQ0MTAwNDM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4410043?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipeflop",
      "html_url": "https://github.com/filipeflop",
      "followers_url": "https://api.github.com/users/filipeflop/followers",
      "following_url": "https://api.github.com/users/filipeflop/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipeflop/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipeflop/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipeflop/subscriptions",
      "organizations_url": "https://api.github.com/users/filipeflop/orgs",
      "repos_url": "https://api.github.com/users/filipeflop/repos",
      "events_url": "https://api.github.com/users/filipeflop/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipeflop/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipematias23",
      "id": 11415688,
      "node_id": "MDQ6VXNlcjExNDE1Njg4",
      "avatar_url": "https://avatars.githubusercontent.com/u/11415688?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipematias23",
      "html_url": "https://github.com/filipematias23",
      "followers_url": "https://api.github.com/users/filipematias23/followers",
      "following_url": "https://api.github.com/users/filipematias23/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipematias23/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipematias23/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipematias23/subscriptions",
      "organizations_url": "https://api.github.com/users/filipematias23/orgs",
      "repos_url": "https://api.github.com/users/filipematias23/repos",
      "events_url": "https://api.github.com/users/filipematias23/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipematias23/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "FilipePfluck",
      "id": 62773200,
      "node_id": "MDQ6VXNlcjYyNzczMjAw",
      "avatar_url": "https://avatars.githubusercontent.com/u/62773200?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/FilipePfluck",
      "html_url": "https://github.com/FilipePfluck",
      "followers_url": "https://api.github.com/users/FilipePfluck/followers",
      "following_url": "https://api.github.com/users/FilipePfluck/following{/other_user}",
      "gists_url": "https://api.github.com/users/FilipePfluck/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/FilipePfluck/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/FilipePfluck/subscriptions",
      "organizations_url": "https://api.github.com/users/FilipePfluck/orgs",
      "repos_url": "https://api.github.com/users/FilipePfluck/repos",
      "events_url": "https://api.github.com/users/FilipePfluck/events{/privacy}",
      "received_events_url": "https://api.github.com/users/FilipePfluck/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipecalegario",
      "id": 299057,
      "node_id": "MDQ6VXNlcjI5OTA1Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/299057?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipecalegario",
      "html_url": "https://github.com/filipecalegario",
      "followers_url": "https://api.github.com/users/filipecalegario/followers",
      "following_url": "https://api.github.com/users/filipecalegario/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipecalegario/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipecalegario/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipecalegario/subscriptions",
      "organizations_url": "https://api.github.com/users/filipecalegario/orgs",
      "repos_url": "https://api.github.com/users/filipecalegario/repos",
      "events_url": "https://api.github.com/users/filipecalegario/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipecalegario/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipecifali",
      "id": 975041,
      "node_id": "MDQ6VXNlcjk3NTA0MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/975041?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipecifali",
      "html_url": "https://github.com/filipecifali",
      "followers_url": "https://api.github.com/users/filipecifali/followers",
      "following_url": "https://api.github.com/users/filipecifali/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipecifali/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipecifali/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipecifali/subscriptions",
      "organizations_url": "https://api.github.com/users/filipecifali/orgs",
      "repos_url": "https://api.github.com/users/filipecifali/repos",
      "events_url": "https://api.github.com/users/filipecifali/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipecifali/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Srubens",
      "id": 21316420,
      "node_id": "MDQ6VXNlcjIxMzE2NDIw",
      "avatar_url": "https://avatars.githubusercontent.com/u/21316420?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Srubens",
      "html_url": "https://github.com/Srubens",
      "followers_url": "https://api.github.com/users/Srubens/followers",
      "following_url": "https://api.github.com/users/Srubens/following{/other_user}",
      "gists_url": "https://api.github.com/users/Srubens/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Srubens/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Srubens/subscriptions",
      "organizations_url": "https://api.github.com/users/Srubens/orgs",
      "repos_url": "https://api.github.com/users/Srubens/repos",
      "events_url": "https://api.github.com/users/Srubens/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Srubens/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "falkTX",
      "id": 1334853,
      "node_id": "MDQ6VXNlcjEzMzQ4NTM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1334853?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/falkTX",
      "html_url": "https://github.com/falkTX",
      "followers_url": "https://api.github.com/users/falkTX/followers",
      "following_url": "https://api.github.com/users/falkTX/following{/other_user}",
      "gists_url": "https://api.github.com/users/falkTX/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/falkTX/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/falkTX/subscriptions",
      "organizations_url": "https://api.github.com/users/falkTX/orgs",
      "repos_url": "https://api.github.com/users/falkTX/repos",
      "events_url": "https://api.github.com/users/falkTX/events{/privacy}",
      "received_events_url": "https://api.github.com/users/falkTX/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipebezerra",
      "id": 1006095,
      "node_id": "MDQ6VXNlcjEwMDYwOTU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1006095?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipebezerra",
      "html_url": "https://github.com/filipebezerra",
      "followers_url": "https://api.github.com/users/filipebezerra/followers",
      "following_url": "https://api.github.com/users/filipebezerra/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipebezerra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipebezerra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipebezerra/subscriptions",
      "organizations_url": "https://api.github.com/users/filipebezerra/orgs",
      "repos_url": "https://api.github.com/users/filipebezerra/repos",
      "events_url": "https://api.github.com/users/filipebezerra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipebezerra/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipemacedo",
      "id": 28747696,
      "node_id": "MDQ6VXNlcjI4NzQ3Njk2",
      "avatar_url": "https://avatars.githubusercontent.com/u/28747696?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipemacedo",
      "html_url": "https://github.com/filipemacedo",
      "followers_url": "https://api.github.com/users/filipemacedo/followers",
      "following_url": "https://api.github.com/users/filipemacedo/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipemacedo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipemacedo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipemacedo/subscriptions",
      "organizations_url": "https://api.github.com/users/filipemacedo/orgs",
      "repos_url": "https://api.github.com/users/filipemacedo/repos",
      "events_url": "https://api.github.com/users/filipemacedo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipemacedo/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipezabala",
      "id": 35049061,
      "node_id": "MDQ6VXNlcjM1MDQ5MDYx",
      "avatar_url": "https://avatars.githubusercontent.com/u/35049061?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipezabala",
      "html_url": "https://github.com/filipezabala",
      "followers_url": "https://api.github.com/users/filipezabala/followers",
      "following_url": "https://api.github.com/users/filipezabala/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipezabala/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipezabala/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipezabala/subscriptions",
      "organizations_url": "https://api.github.com/users/filipezabala/orgs",
      "repos_url": "https://api.github.com/users/filipezabala/repos",
      "events_url": "https://api.github.com/users/filipezabala/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipezabala/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipenatanael",
      "id": 14134758,
      "node_id": "MDQ6VXNlcjE0MTM0NzU4",
      "avatar_url": "https://avatars.githubusercontent.com/u/14134758?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipenatanael",
      "html_url": "https://github.com/filipenatanael",
      "followers_url": "https://api.github.com/users/filipenatanael/followers",
      "following_url": "https://api.github.com/users/filipenatanael/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipenatanael/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipenatanael/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipenatanael/subscriptions",
      "organizations_url": "https://api.github.com/users/filipenatanael/orgs",
      "repos_url": "https://api.github.com/users/filipenatanael/repos",
      "events_url": "https://api.github.com/users/filipenatanael/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipenatanael/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "FFY00",
      "id": 11718923,
      "node_id": "MDQ6VXNlcjExNzE4OTIz",
      "avatar_url": "https://avatars.githubusercontent.com/u/11718923?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/FFY00",
      "html_url": "https://github.com/FFY00",
      "followers_url": "https://api.github.com/users/FFY00/followers",
      "following_url": "https://api.github.com/users/FFY00/following{/other_user}",
      "gists_url": "https://api.github.com/users/FFY00/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/FFY00/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/FFY00/subscriptions",
      "organizations_url": "https://api.github.com/users/FFY00/orgs",
      "repos_url": "https://api.github.com/users/FFY00/repos",
      "events_url": "https://api.github.com/users/FFY00/events{/privacy}",
      "received_events_url": "https://api.github.com/users/FFY00/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "filipe1309",
      "id": 2081014,
      "node_id": "MDQ6VXNlcjIwODEwMTQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2081014?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/filipe1309",
      "html_url": "https://github.com/filipe1309",
      "followers_url": "https://api.github.com/users/filipe1309/followers",
      "following_url": "https://api.github.com/users/filipe1309/following{/other_user}",
      "gists_url": "https://api.github.com/users/filipe1309/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/filipe1309/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/filipe1309/subscriptions",
      "organizations_url": "https://api.github.com/users/filipe1309/orgs",
      "repos_url": "https://api.github.com/users/filipe1309/repos",
      "events_url": "https://api.github.com/users/filipe1309/events{/privacy}",
      "received_events_url": "https://api.github.com/users/filipe1309/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";
